<h1 id="#about">Mon CV</h1>
<section class="flex-2">
    <article class="lex-left">
        <h3>Hard Skills</h3>
        <h4>Intégration - Développement web</h4>
        <p><img class="small-language" src="Assets/img/languages/html.png" alt="html logo"></p>
        <p><img class="small-language" src="Assets/img/languages/css.png" alt="css logo"></p>
        <p><img class="small-language" src="Assets/img/languages/js.jpg" alt="js logo"></p>
        <p><img class="small-language" src="Assets/img/languages/vuejs.jpg" alt="vuejs logo"></p>
        <p><img class="small-language" src="Assets/img/languages/php.jpg" alt="php logo"></p>

        <h4>Bureautique</h4>
        <p>Pack Office / SharePoint / Page / Numbers</p>
        <h4>SIRH</h4>
        <p>People Soft / ADP / Chronos </p>

        <h4>Langues</h4>
        <p>Anglais : courant</p>
        <p>Espagnol : intermédiaire</p>
        <p>Japonais : débutant</p>

        <h4>Connaissances RH</h4>
        <p>SIRH / Réseaux Sociaux d’Entreprise</p>
        <p>Administration du personnel</p>
        <p>Formation</p>

        <h3>Soft Skills</h3>
        <p>Autonomie, réactivité,</p>
        <p>Créativité, résolution de problèmes,</p>
        <p>Curiosité</p>

        <h3>Formations</h3>
        <p>2020-2021</p>
        <p>3 W Academy – Bac +2</p>
        <p>Développeur Intégrateur d’application Web</p>

        <p>2020</p>
        <p>MOOCs</p>
        <p>Openclassroom -« Découvrez le fonctionnement des algorithmes »</p>

        <p>2016 - 2017</p>
        <p>ISGP - BAC +4</p>
        <p>Manager de l’Organisation des Ressources Humaines et des Relations Sociales</p>
        <p>Mémoire sur la Transformation Digitale</p>

        <p>2008-2009
        <p>Université Paris Descartes – BAC+3</p>
        <p>Licence de Psychologie</p>

        <h3>Centres d’interêt</h3>
        Nouvelles Technologies - Cinéma (VO)
        Voyages : Australie et Nouvelle Zélande
    </article>

    <article>
        <h3>Projets Personnels</h3>
        Liens de page à mettre

        <h3>Expériences</h3>
        <h4>Coordinatrice RH 2018 à 2020</h4>
        <p>STANLEY BLACK & DECKER FRANCE SERVICES INDUSTRIE</p>
        <h5>Administration du Personnel</h5>
        <ul>
            <li>Utilisation du SIRH People Soft : onboarding et sortie, modifications et ajouts de données, reportings
            </li>
            <li>Gestion et suivi des alternants et d’une trentaine d’intérimaires, de la recherche à la facturation
                (progiciels de gestion de factures)</li>
        </ul>
        <p>Formation (appui administratif)</p>
        <ul>
        <li>Suivi des formations, du budget de formation, gestion des factures, bilans annuels</li>
        <li> KPI mensuel : retour des questionnaires formation, parcours d’intégration, nouvelle embauche, fiches de poste</li>
       </ul>
        <p>Projets Divers</p>
        <p>Création de tableau de suivi : des factures, des recherches d’intérimaires</p>
        <p>Rédactions de procédures liées au département RH</p>
        <p>Mise à jour du process d’Onboarding</p>

        <h4>Assistante Administrative PSE 2017 à 2018</h4>
        <p> BNP PARIBAS CIB – ALTEDIA FINANCE</p>
        <p> Utilisation de différents SI pour suivre les dossiers de PDV, transmettre les documents de télétravail et
            réceptionner l’avenant de télétravail.</p>
        <p> Gestion du PDV : accords, convention de rupture, charte, gestion des factures</p>
        <p> Gestion du Télétravail : reportings, procédures, contrôles, formation de l'équipe sur le process</p>

        <h4>Assistante Mobilité Internationale et Administration du Personnel 2016</h4>
        <p>ALLIANZ WORLDWIDE PARTNERS SAS => Allianz Partners ASSURANCES</p>
        <p>Administration du Personnel</p>
        <p>Gestion du temps - Chronos : formation des salariés & remontée des anomalies au service SIRH</p>
        <p>Gestion et suivi des dossiers administratifs des nouveaux arrivants, du contrat à la visite médicale</p>
        <p>Gestion du suivi du temps, de l’immigration et du télétravail</p>
        <p>Mobilité Internationale : Expatriés, Impatriés, VIE</p>
        <p>Suivi et gestion des dossiers : sécurité sociale, factures, impôts, immigration</p>
        <p>Projets Divers</p>
        <p>Rédaction de l’affichage obligatoire (déménagement), RGPD</p>
        <p>Rédaction de procédures liées au poste</p>

        <h4>Réceptionniste – Auberge de Jeunesse - Australie 2014</h4>

        <h4>Chargée de Recrutement et Assistante RH 2012 à 2013</h4>
        <p>MCNEXT (ESN Spécialiste Microsoft) => Infeeny INFORMATIQUE</p>
        <p>Recrutement</p>
        <p>Sourcing, entretien (téléphonique et face à face), compte-rendu d’entretien et suivi du candidat</p>
        <p>Participation à des forums d’emploi / job dating ; relations écoles</p>
        <p>Création de documents pour le recrutement : fiche d’appel, compte-rendu d'entretien</p>
        <p>Administration du Personnel</p>
        <p>Accueil des nouveaux salariés, gestion de la visite médicale</p>
    </article>
</section>

