 <div class="sidenav">
     <!-- Attention fontawsome pro -->
     <a href="index.php?page=about" class="menu-one" id="about">
         
         <p>Mon CV</p>
     </a>
     <a href="index.php?page=project" class="menu-two" id="projects">
        
         <p>Mes Projets</p>
     </a>
     <a href="index.php?page=photography" class="menu-three" id="hobbies">
         
         <p>Photographie</p>
     </a>
     <a href="index.php?page=link" class="menu-four" id="links">
        
         <p>Liens utiles</p>
     </a>


        <a href="index.php?page=opinion" class="menu-five" id="opinion">
        
         <p>Votre avis</p>
     </a>
 </div>