 <div class="sidenav">
     <!-- Menu -->
     <a href="index.php?page=about" class="menu-one" id="about">
         <p>Mon Profil <i class="right-aside far fa-address-card"></i></p>
     </a>

     <a href="index.php?page=project" class="menu-two" id="projects">
         <p>Mes Projets <i class="fas fa-book"></i></p>
     </a>

     <a href="index.php?page=photography" class="menu-three" id="hobbies">
         <p>Photographie <i class="fas fa-camera-retro"></i></p>
     </a>


     <a href="index.php?page=link" class="menu-four" id="links">
         <p>Liens utiles <i class="fas fa-link"></i></p>
     </a>

     <a href="index.php?page=opinion" class="menu-five" id="opinion">
         <p>Votre avis <i class="fas fa-thumbs-up"></i></p>
     </a>
 </div>