 <div class="sidenav">
     <!-- Attention fontawsome pro -->
     <a href="index.php?page=page#about" class="menu-one" id="about">
         
         <p>Mon CV</p>
     </a>
     <a href="index.php?page=page#projects" class="menu-two" id="projects">
        
         <p>Mes Projets</p>
     </a>
     <a href="index.php?page=page#photos" class="menu-three" id="hobbies">
         
         <p>Photographie</p>
     </a>
     <a href="index.php?page=page#links" class="menu-four" id="links">
        
         <p>Liens utiles</p>
     </a>
 </div>