<section class="information">
    <div> <?php (isset($_GET['response']))? $_GET['response'] : "" ;?>
    </div>

    <h3 id="contact">Contactez-moi</h3>
    <div>
        <a href="mailto:flaviaf91@gmail.com">
            <i class="fas fa-envelope"></i></a>

        <a href="https://fr.linkedin.com/in/flaviafontaineit/fr" target="_blank"
            title="S'ouvre dans un  nouvel onglet vers la page Linkedin">
            <i class="fab fa-linkedin"></i></a>

        <a href="https://github.com/FlavF" target="_blank" title="S'ouvre dans un  nouvel onglet vers la page Linkedin">
            <i class="fab fa-github"></i></a>

        <a href=""><i class="far fa-comment"></i></a>


    </div>



</section>

<section class="end-footer">
    Copyright FlaviaDev © 2021
</section>


<div class="modal hidden">
    <center>
        <h1>Message</h1>

        <form action="index.php?page=formMessage" method="post">
            <p>
                <label for="email">Email</label>
                <input type="text" name="email" id="email">
            </p>
            <p>
                <label for="name">Prénom</label>
                <input type="text" name="name" id="name">
            </p>

            <p>
                Message:
            </p>
            <p>
                <textarea rows="5" name="message" cols="30"></textarea>
            </p>
            <p>
                <input type="submit" name="submit" value="Envoyer">
            </p>
        </form>
          <div> <?php if(isset($_GET['response'])): ?>
        <?= $_GET['response'] ?>
        <?php endif; ?>
    </div>
    </center>
</div>