<section class="information">
    <div> <?php (isset($_GET['response']))? $_GET['response'] : "" ;?>
    </div>

    <h3 id="contact">Contactez-moi</h3>
    <div>
        <!--Email link -->
        <a href="mailto:flaviaf91@gmail.com">
            <i class="fas fa-envelope"></i></a>
        <!--Linkedin link -->
        <a href="https://fr.linkedin.com/in/flaviafontaineit/fr" target="_blank"
            title="S'ouvre dans un  nouvel onglet vers la page Linkedin">
            <i class="fab fa-linkedin"></i></a>
        <!--Git link -->
        <a href="https://github.com/FlavF" target="_blank" title="S'ouvre dans un  nouvel onglet vers la page Linkedin">
            <i class="fab fa-github"></i></a>
        <!--To write to me link -->
        <span id="message"><i class="far fa-comment"></i></span>
    </div>



</section>

<section class="end-footer">
    Copyright FlaviaDev©2021
</section>

<div id="modal" class="hidden">
    <div class="modal-content">
        <h1>Message</h1>
         <span class="close">&times;</span>
        <form action="index.php?page=formMessage" method="post">
            <p>
                <label for="email">Email</label>
                <input type="text" name="email" id="email">
            </p>
            <p>
                <label for="name">Prénom</label>
                <input type="text" name="name" id="name">
            </p>

            <p>
                Message:
            </p>
            <p>
                <textarea rows="5" name="message" cols="30"></textarea>
            </p>
            <p>
                <input type="submit" name="submit" value="Envoyer">
            </p>
        </form>
        <div> <?php if(isset($_GET['response'])): ?>
            <?= $_GET['response'] ?>
            <?php endif; ?>
        </div>
    </div>
</div>