<section class="information">

    <div> <?php (isset($_GET['response'])) ? $_GET['response'] : ""; ?>
    </div>

    <h3 id="contact">Contactez-moi</h3>
    <div>
        <!--Linkedin link -->
        <a href="https://fr.linkedin.com/in/flaviafontaineit/fr" target="_blank" title="S'ouvre dans un  nouvel onglet vers la page Linkedin">
            <i class="fab fa-linkedin"></i></a>
        <!--Git link -->
        <a href="https://github.com/FlavF" target="_blank" title="S'ouvre dans un  nouvel onglet vers la page Linkedin">
            <i class="fab fa-github"></i></a>
        <!--To write to me link -->
        <span>
            <a href="index.php?page=message" id="message">
                <i class="far fa-comment"></i>
            </a>
        </span>
        <div>
            <em>Dernière mise à jour le 23 juin 2022</em>
        </div>
    </div>
</section>