<div class="header">
    <a href="index.php" alt="page d'accueil"><img class="logo" src="Assets/img/logo/LogoFlaviaDev-1.png" alt="logo"></a>
    <p> 
    <?php
    setlocale(LC_TIME, 'fr_FR');
    date_default_timezone_set('Europe/Paris');
    // echo strftime('%A %d %B %Y, %H:%M');
    echo date('l jS \of F Y h:i:s A');
    ?> 
    </p>
   
    <div>
        <input type="checkbox" name="darkmode" id="darkmode" class="darkmodes">
        <label for="darkmode" class="dark">
             
             <i class="fa-regular fa-sun"></i>
             <i class="fa-regular fa-moon"></i>
            <div class="ball"></div>
        </label>
    </div>

  
</div>