<div class="home">
    <div class="welcome">
    <p>Bienvenue</p>
    <p>Je m'appelle Flavia et ceci est mon portfolio</p>
    <p>Je suis :</p>
    <p>Développeuse Web Full Stack / Développeuse Back-end</p>
      <img class="left-arrow" src="Assets/img/left.png" alt="left arrow">
</div>
<div class="menus">
    <p>Ce que vous pouvez trouver sur mon portfolio =></p>
     <a href="index.php?page=about" class="menu-one" id="about">
         <p>Mon Profil vous intéresse ? Venez en savoir un peu plus sur cette page <i class="right-aside far fa-address-card"></i></p>
     </a>

     <a href="index.php?page=project" class="menu-two" id="projects">
         <p>Voici quelques uns de mes projets <i class="fas fa-book"></i></p>
     </a>

     <a href="index.php?page=photography" class="menu-three" id="hobbies">
         <p>Une de mes passions, la photographie <i class="fas fa-camera-retro"></i></p>
     </a>


     <a href="index.php?page=link" class="menu-four" id="links">
         <p>Vous souhaitez en savoir plus sur le développement, vous trouverez des liens utiles en suivant ce lien <i class="fas fa-link"></i></p>
     </a>

     <a href="index.php?page=opinion" class="menu-five" id="opinion">
         <p>Je vous remercie d'avoir passer quelques instants sur mon portfolio, voulez vous laisser un petit smiley ? <i class="fas fa-thumbs-up"></i></p>
     </a>

     <a href="index.php?page=message">
         <p>Voulez-vous me laisser un message ? <i class="far fa-comment"></i></p>
     </a>
</div>
  
</div>