<section >
    <h1 id="#links">Liens utiles</h1>

    <div class="links">
    
    <!-- Tags -->
    <?php foreach($tags as $tag): ?>
    <article class="category">
        <table>
            <caption><?=htmlspecialchars($tag['tag']) ?></caption>
            <tbody>
                <?php foreach($links as $link): ?>
                <tr>
                    <?php if(isset($link['link'])) :?>
                        <?php if($tag['id_tag'] === $link['id_tag']) :?>
                            <td>
                                <a href="<?=htmlspecialchars($link['url']) ?>" title="<?=htmlspecialchars($link['title']) ?>" target="_blank"><?=htmlspecialchars($link['link']) ?></a>
                            </td>
                        <?php endif; ?>
                    <?php else: ?>
                        <td> Pas de liens ajoutés</td>
                    <?php endif; ?>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </article>
     <?php endforeach; ?>
     </div>
</section>