<h1 id="#projects">Projets</h1>
<section>
    <article class="project">
        <h2>Velib</h2>
        <p> résumé</p>
       <a href="">
        <img src="" alt="image"></a>
    </article>
    <article class="project">
        <h2>Annuaire</h2>
        <p> résumé</p>
       <a href="">
        <img src="" alt="image"></a>
    </article>
    <article class="project">
        <h2>Yogassages</h2>
        <p> résumé</p>
       <a href="">
        <img src="" alt="image"></a>
    </article>
    <article class="project">
        <h2></h2>
    </article>
</section>
