<h1 id="#projects">Projets</h1>

<!-- Filter -->
=> créer des tags html, css et si coché voir seulement les projets liés


<section>

<?php foreach ($projects as $project): ?>
    <article class="project">
        <h2><?=htmlspecialchars($project['project']) ?></h2>
        <p><?=htmlspecialchars($project['description']) ?></p>
       <a href="">
        <img src="<?=htmlspecialchars($project['src']) ?>" alt="<?=htmlspecialchars($project['alt']) ?>"></a>
        <!-- Tag languages -->
        <p> <?php foreach ($languages as $language): ?>
            <?php if($language['project'] === $project['project']): ?>
        <?=htmlspecialchars($language['languages_IT']) ?>
        <?php endif; ?>
        <?php endforeach; ?>
        </p>
    </article>
<?php endforeach; ?>
</section>
